const TAGS = {
  ELECTRONICS: [
    // Mobile & Communication
    "smartphones",
    "phones",
    "cell phones",
    "mobile phones",
    "phone cases",
    "phone accessories",
    "phone chargers",
    "phone cables",
    "screen protectors",
    "smartwatches",
    "smart watch",
    "fitness trackers",
    "wearable tech",

    // Computers & Accessories
    "laptops",
    "desktop computers",
    "computer",
    "pc",
    "gaming pc",
    "all-in-one computers",
    "tablets",
    "ipad",
    "computer parts",
    "pc parts",
    "motherboards",
    "processors",
    "cpu",
    "graphics cards",
    "gpu",
    "ram",
    "memory",
    "hard drives",
    "ssd",
    "hdd",
    "storage",
    "disks",
    "computer accessories",
    "keyboards",
    "mice",
    "computer mouse",
    "monitors",
    "webcams",
    "speakers",
    "computer speakers",
    "printers",
    "printer",
    "scanners",
    "networking",
    "routers",
    "wifi routers",
    "modems",

    // Gaming
    "consoles",
    "gaming console",
    "game console",
    "playstation",
    "xbox",
    "nintendo switch",
    "gaming accessories",
    "gaming headsets",
    "gaming keyboards",
    "gaming mice",
    "gaming chairs",
    "controllers",
    "game controllers",
    "vr headsets",
    "virtual reality",

    // TV & Audio
    "television",
    "TV",
    "smart tv",
    "4k tv",
    "oled tv",
    "led tv",
    "streaming devices",
    "roku",
    "apple tv",
    "fire stick",
    "home theater",
    "sound bars",
    "home audio",
    "headphones",
    "earphones",
    "earbuds",
    "wireless headphones",
    "bluetooth headphones",
    "noise cancelling headphones",

    // Home Appliances (Electronics)
    "smart home",
    "smart speakers",
    "alexa",
    "google home",
    "smart lights",
    "smart plugs",
    "security cameras",
    "smart thermostats",
    "smart locks",
    "home automation",
    "smart doorbells",
    "air purifiers",
    "humidifiers",
    "dehumidifiers",
    "fans",
    "electric fans",
    "space heaters",

    // Kitchen Electronics
    "microwave",
    "microwaves",
    "toaster",
    "toasters",
    "coffee makers",
    "blenders",
    "food processors",
    "electric kettles",
    "rice cookers",
    "slow cookers",
    "air fryers",
    "electric grills",
    "juicers",
    "mixers",
    "bread makers",
    "electric can openers",

    // Large Appliances
    "refrigerator",
    "fridge",
    "freezer",
    "washing machine",
    "washer",
    "dryer",
    "dishwasher",
    "oven",
    "stove",
    "range",
    "cooktop",
    "range hood",
    "garbage disposal",
    "water heater",

    // Camera & Photo
    "cameras",
    "digital cameras",
    "dslr cameras",
    "mirrorless cameras",
    "action cameras",
    "gopro",
    "camera lenses",
    "tripods",
    "camera accessories",
    "photo equipment",
    "camcorders",
    "video cameras",
  ],

  FASHION: [
    // Women's Clothing
    "women clothes",
    "womens clothing",
    "women's fashion",
    "dresses",
    "dress",
    "blouses",
    "tops",
    "women's shirts",
    "women's t-shirts",
    "sweaters",
    "cardigans",
    "hoodies",
    "sweatshirts",
    "jeans",
    "pants",
    "trousers",
    "leggings",
    "skirts",
    "shorts",
    "swimwear",
    "bikinis",
    "lingerie",
    "bras",
    "underwear",
    "sleepwear",
    "pajamas",
    "robes",
    "activewear",
    "workout clothes",
    "yoga pants",
    "sports bras",
    "maternity wear",
    "plus size clothing",
    "petite clothing",

    // Men's Clothing
    "men clothes",
    "mens clothing",
    "men's fashion",
    "men's shirts",
    "dress shirts",
    "polo shirts",
    "t-shirts",
    "t-shirt",
    "tank tops",
    "henley shirts",
    "sweaters",
    "hoodies",
    "sweatshirts",
    "suits",
    "suit",
    "blazers",
    "sport coats",
    "pants",
    "dress pants",
    "chinos",
    "jeans",
    "shorts",
    "underwear",
    "boxers",
    "briefs",
    "undershirts",
    "socks",
    "ties",
    "bow ties",
    "belts",
    "swimwear",
    "swim trunks",
    "activewear",
    "workout clothes",
    "athletic wear",

    // Shoes
    "shoes",
    "sneakers",
    "running shoes",
    "athletic shoes",
    "dress shoes",
    "boots",
    "sandals",
    "flip flops",
    "loafers",
    "high heels",
    "flats",
    "wedges",
    "pumps",
    "slippers",
    "work boots",
    "hiking boots",
    "winter boots",

    // Accessories
    "handbags",
    "purses",
    "backpacks",
    "wallets",
    "watches",
    "jewelry",
    "necklaces",
    "earrings",
    "bracelets",
    "rings",
    "sunglasses",
    "eyewear",
    "hats",
    "caps",
    "scarves",
    "gloves",
    "mittens",
    "hair accessories",

    // Outerwear
    "jackets",
    "coats",
    "winter coats",
    "parkas",
    "raincoats",
    "windbreakers",
    "vests",
    "blazers",
  ],

  HOME_GARDEN: [
    // Bedroom
    "beds",
    "bed",
    "mattresses",
    "bed frames",
    "headboards",
    "bedding",
    "bed sheets",
    "sheet sets",
    "pillows",
    "pillow cases",
    "comforters",
    "duvet covers",
    "blankets",
    "throws",
    "bedroom furniture",
    "nightstands",
    "dressers",
    "wardrobes",
    "closets",

    // Living Room
    "sofas",
    "couches",
    "couch",
    "sectionals",
    "loveseats",
    "recliners",
    "chairs",
    "armchairs",
    "coffee tables",
    "end tables",
    "side tables",
    "tv stands",
    "tv station",
    "entertainment centers",
    "bookcases",
    "shelving",
    "ottomans",
    "living room furniture",

    // Dining Room
    "dining tables",
    "table",
    "dining chairs",
    "bar stools",
    "dining sets",
    "buffets",
    "china cabinets",
    "serving carts",
    "dining room furniture",

    // Kitchen
    "kitchen tables",
    "mini table",
    "kitchen islands",
    "kitchen carts",
    "bar tables",
    "kitchen stools",
    "cookware",
    "pots and pans",
    "bakeware",
    "kitchen utensils",
    "knives",
    "cutting boards",
    "dinnerware",
    "plates",
    "bowls",
    "cups",
    "mugs",
    "glassware",
    "silverware",
    "flatware",

    // Bathroom
    "bathroom furniture",
    "vanities",
    "medicine cabinets",
    "bathroom storage",
    "shower curtains",
    "bath towels",
    "hand towels",
    "washcloths",
    "bath mats",
    "bathroom rugs",
    "toilet paper holders",
    "towel racks",

    // Home Decor
    "wall art",
    "paintings",
    "prints",
    "mirrors",
    "clocks",
    "picture frames",
    "candles",
    "vases",
    "decorative bowls",
    "sculptures",
    "figurines",
    "artificial plants",
    "fake plants",
    "artificial flowers",
    "decorative pillows",
    "curtains",
    "drapes",
    "blinds",
    "window treatments",
    "rugs",
    "area rugs",
    "carpets",
    "runners",
    "lighting",
    "lamps",
    "ceiling fans",
    "chandeliers",
    "pendant lights",

    // Garden & Outdoor
    "garden furniture",
    "patio furniture",
    "outdoor chairs",
    "outdoor tables",
    "umbrellas",
    "gazebos",
    "grills",
    "bbq grills",
    "outdoor cooking",
    "fire pits",
    "outdoor heaters",
    "garden tools",
    "lawn mowers",
    "trimmers",
    "pruning shears",
    "watering cans",
    "garden hoses",
    "sprinklers",
    "planters",
    "flower pots",
    "garden soil",
    "fertilizer",
    "seeds",
    "plants",
    "flowers",
    "trees",
    "shrubs",
    "outdoor lighting",
    "solar lights",
    "outdoor decor",

    // Storage & Organization
    "storage boxes",
    "storage bins",
    "organizers",
    "closet organizers",
    "shoe racks",
    "hangers",
    "laundry baskets",
    "hampers",
    "storage cabinets",
    "storage shelves",
  ],

  SPORTS: [
    "fitness equipment",
    "exercise equipment",
    "treadmills",
    "elliptical machines",
    "exercise bikes",
    "weight sets",
    "dumbbells",
    "barbells",
    "resistance bands",
    "yoga mats",
    "yoga blocks",
    "foam rollers",
    "pull up bars",
    "basketball",
    "football",
    "soccer",
    "baseball",
    "tennis",
    "golf",
    "golf clubs",
    "golf balls",
    "camping gear",
    "tents",
    "sleeping bags",
    "backpacks",
    "hiking boots",
    "fishing gear",
    "fishing rods",
    "tackle boxes",
    "hunting gear",
    "bikes",
    "bicycles",
    "scooters",
    "skateboards",
    "roller blades",
    "swimming gear",
    "goggles",
    "swimsuits",
    "water sports",
    "kayaks",
    "paddleboards",
    "winter sports",
    "skis",
    "snowboards",
    "ice skates",
    "team sports",
    "athletic wear",
    "sports shoes",
    "sports accessories",
  ],

  HEALTH_BEAUTY: [
    "skincare",
    "face wash",
    "moisturizer",
    "sunscreen",
    "anti aging cream",
    "serums",
    "toners",
    "cleansers",
    "exfoliators",
    "face masks",
    "makeup",
    "foundation",
    "concealer",
    "mascara",
    "eyeliner",
    "eyeshadow",
    "lipstick",
    "lip gloss",
    "blush",
    "bronzer",
    "nail polish",
    "hair care",
    "shampoo",
    "conditioner",
    "hair styling",
    "hair dryers",
    "straighteners",
    "curling irons",
    "hair brushes",
    "combs",
    "hair accessories",
    "fragrances",
    "perfume",
    "cologne",
    "body spray",
    "deodorant",
    "antiperspirant",
    "body wash",
    "soap",
    "bath bombs",
    "lotion",
    "body cream",
    "hand cream",
    "oral care",
    "toothbrush",
    "toothpaste",
    "mouthwash",
    "dental floss",
    "vitamins",
    "supplements",
    "protein powder",
    "health monitors",
    "thermometers",
    "blood pressure monitors",
    "first aid",
    "bandages",
    "pain relievers",
    "allergy medicine",
    "cold medicine",
    "beauty tools",
    "makeup brushes",
    "tweezers",
    "nail clippers",
    "razors",
    "shaving cream",
    "electric shavers",
  ],

  AUTOMOTIVE: [
    "car parts",
    "engine parts",
    "brake parts",
    "suspension parts",
    "exhaust parts",
    "filters",
    "oil filters",
    "air filters",
    "spark plugs",
    "batteries",
    "car batteries",
    "tires",
    "wheels",
    "rims",
    "car accessories",
    "car electronics",
    "car stereos",
    "gps",
    "dash cams",
    "car chargers",
    "phone mounts",
    "seat covers",
    "floor mats",
    "steering wheel covers",
    "car organizers",
    "car cleaning",
    "car wash",
    "car wax",
    "car polish",
    "tire shine",
    "automotive tools",
    "socket sets",
    "wrenches",
    "screwdrivers",
    "jump starters",
    "tire pressure gauges",
    "car jacks",
    "motor oil",
    "transmission fluid",
    "coolant",
    "brake fluid",
    "windshield wipers",
    "car lights",
    "headlights",
    "tail lights",
    "car mirrors",
    "truck accessories",
    "motorcycle parts",
    "motorcycle accessories",
  ],

  BOOKS: [
    "fiction books",
    "non fiction books",
    "novels",
    "romance novels",
    "mystery books",
    "thriller books",
    "science fiction",
    "fantasy books",
    "horror books",
    "biographies",
    "autobiographies",
    "history books",
    "self help books",
    "business books",
    "cookbooks",
    "diet books",
    "health books",
    "travel books",
    "art books",
    "photography books",
    "children's books",
    "picture books",
    "young adult books",
    "teen books",
    "educational books",
    "textbooks",
    "reference books",
    "dictionaries",
    "encyclopedias",
    "comics",
    "graphic novels",
    "manga",
    "poetry books",
    "religious books",
    "spiritual books",
    "philosophy books",
    "psychology books",
    "science books",
    "technology books",
    "computer books",
    "programming books",
    "magazines",
    "newspapers",
    "journals",
    "ebooks",
    "audiobooks",
  ],

  TOYS: [
    "action figures",
    "dolls",
    "barbie dolls",
    "stuffed animals",
    "teddy bears",
    "plush toys",
    "building blocks",
    "lego",
    "construction toys",
    "puzzles",
    "jigsaw puzzles",
    "board games",
    "card games",
    "video games",
    "educational toys",
    "learning toys",
    "electronic toys",
    "remote control toys",
    "rc cars",
    "drones",
    "toy cars",
    "toy trucks",
    "trains",
    "model trains",
    "play sets",
    "dollhouses",
    "play kitchens",
    "pretend play",
    "dress up costumes",
    "arts and crafts",
    "coloring books",
    "crayons",
    "markers",
    "paint sets",
    "clay",
    "outdoor toys",
    "playground equipment",
    "swing sets",
    "trampolines",
    "water toys",
    "pool toys",
    "beach toys",
    "sports toys",
    "balls",
    "frisbees",
    "kites",
    "bikes for kids",
    "scooters for kids",
    "ride on toys",
    "baby toys",
    "toddler toys",
    "infant toys",
    "rattles",
    "teething toys",
    "musical toys",
    "toy instruments",
    "science kits",
    "chemistry sets",
    "microscopes",
    "telescopes",
    "robot toys",
    "collectible toys",
    "trading cards",
  ],

  ENTERTAINMENT: [
    "movies",
    "dvds",
    "blu ray",
    "4k movies",
    "tv shows",
    "music",
    "cds",
    "vinyl records",
    "digital music",
    "streaming subscriptions",
    "concert tickets",
    "event tickets",
    "movie tickets",
    "musical instruments",
    "guitars",
    "keyboards",
    "drums",
    "violins",
    "pianos",
    "amplifiers",
    "microphones",
    "music accessories",
    "sheet music",
    "music books",
    "karaoke machines",
    "record players",
    "turntables",
    "dj equipment",
    "mixers",
    "party supplies",
    "decorations",
    "balloons",
    "party games",
    "costume accessories",
    "magic tricks",
    "novelty items",
    "collectibles",
    "memorabilia",
    "trading cards",
    "comic books",
  ],

  PETS: [
    "dog food",
    "cat food",
    "pet food",
    "dog treats",
    "cat treats",
    "pet treats",
    "dog toys",
    "cat toys",
    "pet toys",
    "dog beds",
    "cat beds",
    "pet beds",
    "pet carriers",
    "dog carriers",
    "cat carriers",
    "pet crates",
    "dog crates",
    "leashes",
    "dog leashes",
    "collars",
    "dog collars",
    "cat collars",
    "harnesses",
    "pet harnesses",
    "pet gates",
    "litter boxes",
    "cat litter",
    "pet litter",
    "pet grooming",
    "dog grooming",
    "cat grooming",
    "pet brushes",
    "pet shampoo",
    "nail clippers",
    "pet health",
    "pet supplements",
    "flea treatment",
    "tick prevention",
    "pet medication",
    "aquariums",
    "fish tanks",
    "fish food",
    "aquarium accessories",
    "bird cages",
    "bird food",
    "bird toys",
    "small animal cages",
    "hamster cages",
    "rabbit cages",
    "reptile terrariums",
    "reptile heating",
    "pet training",
    "training treats",
    "training pads",
    "pet cleanup",
    "waste bags",
    "pet odor eliminators",
    "pet clothing",
    "dog clothes",
    "pet costumes",
    "pet accessories",
    "pet ID tags",
    "pet monitoring cameras",
  ],

  OFFICE: [
    "office chairs",
    "desk chairs",
    "desks",
    "office desks",
    "standing desks",
    "computer desks",
    "office furniture",
    "filing cabinets",
    "bookcases",
    "office storage",
    "desk organizers",
    "pen holders",
    "paper trays",
    "staplers",
    "hole punchers",
    "paper clips",
    "binders",
    "folders",
    "file folders",
    "notebooks",
    "notepads",
    "sticky notes",
    "pens",
    "pencils",
    "markers",
    "highlighters",
    "erasers",
    "rulers",
    "scissors",
    "tape",
    "glue",
    "paper",
    "copy paper",
    "printer paper",
    "envelopes",
    "labels",
    "stamps",
    "calculators",
    "shredders",
    "laminators",
    "binding machines",
    "office electronics",
    "phones",
    "office phones",
    "fax machines",
    "scanners",
    "copiers",
    "projectors",
    "presentation boards",
    "whiteboards",
    "markers for whiteboards",
    "calendars",
    "planners",
    "appointment books",
    "desk pads",
    "mouse pads",
    "computer accessories",
    "cable management",
    "surge protectors",
    "power strips",
    "office lighting",
    "desk lamps",
    "task lighting",
    "office supplies",
    "business cards",
    "letterhead",
    "invoice books",
    "receipt books",
    "shipping supplies",
    "packaging materials",
    "bubble wrap",
    "packing tape",
    "boxes",
    "mailing tubes",
    "office cleaning supplies",
    "disinfectant wipes",
    "air fresheners",
    "trash cans",
    "recycling bins",
  ],
};

module.exports = TAGS;
